git_toprepo.py
git_toprepo_test.py

`remote.origin.url` is needed by git-submodule to resolve relative URLs. Therefore, set it correctly, set `remote.origin.pushUrl` to /dev/null, to avoid accidental erroneous pushes, and provide a new `remote.top.pushUrl` for power users to use `git push top` directly.
This commit reads and updates the `.git/config` file for backwards compatibility. That part will be reverted soon again.

Set remote origin url

---

git_toprepo.py

In the backwards compatible mode, remote.url.pushUrl=/dev/null should also be populated.

Fix write remote.url.pushUrl as /dev/null

---

build.sh
git_filter_repo_for_toprepo.py
git_toprepo.py
poetry.lock
pyproject.toml

Instead of having git-filter-repo as a dependency, just bundle it with the code base. It turned out that the latest release 2.38 does not support Git 2.43 or newer.
The downloaded package is called git_filter_repo_for_toprepo to avoid potential installation conflicts.

Bundle latest git-filter-repo

---

git_toprepo.py
pyproject.toml

https://github.com/python-poetry/poetry-core/pull/773 merge 2024-10-13 stopped including "include" files into wheels by default. This update adds git_filter_repo_for_toprepo.py back into the wheel.
Fixes #38

Fix pyproject.toml to include git_filter_repo_for_toprepo

---

README.md
src/cli.rs
src/config.rs
src/main.rs
src/repo.rs
src/util.rs

Let `git-toprepo init` initialize the git-config toprepo.config with a sane value. Then there is no need for auto-resolving a config location in case it is not configured. Another benefit is that git-toprepos can be identified by checking for the existence of the git-config key `toprepo.config`.

Make the git-config toprepo.config mandatory

---

src/cli.rs
src/main.rs

We can make `git toprepo push` fail early in command line parsing because of a couple of reasons:
* git-toprepo currently only supports using gerrit.
* creating a gerrit change requires commits to be pushed to a `refs/for/` namespace, and specifying refspec requires specifying the remote: git push origin HEAD:refs/for/master
Therefore since `git-toprepo push` aims to support the same workflow as `git push` we can make the remote and refspec(s) required for `git toprepo push`.

Require remote and refspec for push commands

---

src/cli.rs
src/config.rs
src/git.rs
src/main.rs
tests/integration/config.rs
tests/integration/fixtures/toprepo.rs
tests/integration/main.rs

This can be used if the main configuration is invalid. Otherwise the main dispatch would not reach the config-validation code for the error with the repo's own config. Regardless of the validity of the user provided config file.

Validate user-provided config files before loading the repo itself

---

flake.nix

Even better would be to use the git hash.

Set version 0.0.0 in Nix build, not 0.1.0

---

src/loader.rs
src/log.rs
src/main.rs
src/repo.rs

`ErrorMode` has a cleaner interface than an anonymous `AtomicBool`.

Use ErrorMode instead of interrupted AtomicBool

---

.github/workflows/ci.yaml
.github/workflows/release.yaml

The text "_Build and test / Build for x86_64-unknown-linux-musl_" is too repetitive. "_ci / build (x86_64-unknown-linux-musl)_" gives an improved overview.

Rename build-and-test workflow to ci for cleaner UI

---

src/util.rs

`debug_assert_eq!()` should be used instead of
```
[cfg(test)]
assert_eq!()
```
Then the assert is used in non-optimized code, not just when testing non-optimized code.

Change [cfg(test)] assert() to debug_assert()

---

.gitignore
Cargo.lock
Cargo.toml
flake.nix
lib/testtools/Cargo.toml
lib/testtools/lib.rs
lib/testtools/test_util.rs
src/config.rs
src/git_fast_export_import.rs
src/main.rs
tests/integration/clone.rs
tests/integration/config.rs
tests/integration/dump.rs
tests/integration/fetch.rs
tests/integration/fixtures/toprepo.rs
tests/integration/push.rs

This also adds a new git-toprepo-testtools crate to share test code.

Use GIT_TOPREPO_KEEP_TEMP_DIR=1 to persist test dirs

---

src/git_fast_export_import.rs
src/loader.rs
src/log.rs
src/main.rs
src/repo.rs

Extract the keep-going logic from the logging framework into a new `ErrorObserver` which counts the errors. The new code will return the error in fail-fast mode and swallow errors in keep-going mode.

Restructured fast-fail and keep-going

---

src/repo.rs
tests/integration/fetch.rs

If just a single ref is filtered, other refs should not be removed.

Only remove refs when filtering all refs

---

src/cli.rs
src/config.rs
src/loader.rs
src/main.rs
tests/integration/config.rs

This fixes the initial cloning and bootstrapping scenario, setting the correct .gittoprepo.toml ref in the git-config. An integration test running `git-toprepo clone` followed by `git-toprepo config bootstrap` is verifying that procedure.

Integration test config-bootstrap procedure

---

src/loader.rs
src/repo.rs
src/repo_cache_serde.rs
src/util.rs

By moving the error, it is possible to check if the error is fixable at a specific revision, e.g. a tip of a branch. In git-fast-export, it is only available when it is changing and cannot be checked at an arbritrary revision.
This prepares for hiding unfixable warnings.

Move .gitmodules mode error from git-fast-export to loader

---

src/loader.rs
src/log.rs
src/main.rs
src/repo.rs

With a closure to execute the task, there is no risk of forgetting to check if errors occurred or not.

Use a closure in ErrorObserver

---

src/expander.rs
src/loader.rs
src/main.rs
src/push.rs
src/repo.rs

`MonoRepoProcessor` is now simply a container of stuff useful during processing.
Also fixed a double call to `unique()` for `old_and_new_monorefs`.

Move refilter code from MonoRepoProcessor to expander.rs

---

src/expander.rs
src/repo.rs
src/repo_cache_serde.rs

MonoRepoCommitId and TopRepoCommitId are just wrapping gix::ObjectId and are so small that .clone() is unnecessary. Let's use the Copy trait instead.

Tidy: Implement Copy trait for *CommitId structs

---

src/expander.rs
src/repo.rs
src/repo_cache_serde.rs

When the filtering failed, the cache mapping from mono commit object to and from mono commit id had got new entries but not the top_to_mono_map. Then, serialization of the cache failed.
This mitigates that problem by populating all three maps at the same time, when the object and the id are both available.

Keep the commit cache maps in sync

---

src/loader.rs
tests/integration/refilter.rs

git-submodule creates an empty directory for each submodule. In case a submodule is substituted for an empty tree with git-toprepo, that directory will disappear. User tooling might depend on the existance of that empty directory, e.g. for each submodule mentioned in `.gitmodules`.
This commit prints a warning to make the user aware of the problem, so that a dummy file can be added to the submodule as a fix.

Warn for empty submodule commit trees

---

src/config.rs
src/git.rs
src/main.rs
src/repo.rs
tests/integration/clone.rs
tests/integration/commit_message.rs
tests/integration/config.rs
tests/integration/dump.rs
tests/integration/fetch.rs
tests/integration/log.rs
tests/integration/push.rs
tests/integration/refilter.rs

Avoid using the user git-config and set environment variables in all calls to git during testing to make all tests deterministic.
Fixes #169.

Make all git calls deterministic during testing

---

src/main.rs
src/repo.rs
src/repo_cache_serde.rs
tests/integration/dump.rs

Also move it to the .git folder of the main worktree as fetching is done in the common .git directory.

Move cache to .git/toprepo/import-cache.bincode

---

src/cli.rs
src/main.rs

The previous print was not helpful:
$ git-toprepo xxx
error: invalid value 'xxx' for '[git]'
[possible values: git]
The new print is better:
$ git-toprepo xxx
error: unrecognized subcommand 'xxx'
Usage: git-toprepo [OPTIONS] <COMMAND>
Fixes #207

Move the optional 'git' argument better help print

---

src/cli.rs
src/main.rs
tests/integration/info.rs

The 'cwd' is not important enough to keep as a stable API in the 'info' subcommand. Move it to the debugging interface 'dump'.
Fixes #210

Move 'git-toprepo info cwd' to 'dump cwd'

---

src/push.rs
tests/integration/fetch.rs
tests/integration/fixtures/make_minimal_with_two_submodules.sh
tests/integration/push.rs
tests/integration/recombine.rs

The normal case is that a mono commit only has mono commits as parents. This fixes the edge case when an original submodule commit is a parent, basically when a submodule is added.

Allow pushing with an original submodule commit as parent

---

src/loader.rs
tests/integration/fetch.rs
tests/integration/log.rs
tests/integration/recombine.rs

It is too hard to track down the origin of the warning if the super repo is unknown.

Show references to super repo in missing commit warnings
